version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    networks:
      - webnet
    restart: unless-stopped
  
  nginx:
    build:
      context: .
      dockerfile: nginx.Dockerfile
    ports:
      - '80:80'
    networks:
      - webnet
    depends_on:
      - app
    restart: unless-stopped
  
networks:
  webnet: